//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatchDetail
    {
        public int PatchID { get; set; }
        public string PatchNo { get; set; }
        public string PatchVersion { get; set; }
        public string CVE { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Severity { get; set; }
        public string Link { get; set; }
        public Nullable<int> AppID { get; set; }
        public System.DateTime Pubdate { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.DateTime> DeployedOn { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string productsAffected { get; set; }
    }
}
